### ISSUE TITLE
You have a date variable wrong

### ISSUE THREAD

**Issue by anthubbard** [statamic/statamic-cheat-sheet#26]
Gents, it is my belief that there is a date variable wrong in the cheatsheet.

http://statamic.github.io/statamic-cheat-sheet/

Go to 'date formatting' and look at 'day: 1 to 31' - the variable says 'L' but it should be 'j' (so I'm told).

**Comment by 0xgdr** [comment]
Thanks Ant, fixed!

**Comment by anthubbard** [comment]
\O/
